source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ReaderReddit' do
    pod 'Alamofire'
    pod 'Kingfisher', '~> 3.0'
    pod 'SwiftyJSON'
    pod 'Floaty'
end
